### ISSUE TITLE
Horizontal scroll support

### ISSUE THREAD

**Issue by pinkeyyy** [MarcStan/monogame-framework-wpfinterop#19]
MonoGame introduced horizontal scroll support in this PR: https://github.com/MonoGame/MonoGame/pull/5735

The way we're pulling in mouse state in WpfMouse is currently missing this information.

EDIT: I had a quick look at this and hoped there would be a simple HorizontalScrollWheel event we could use, sadly not. Though I did hash out something that appeared to work from SO: https://stackoverflow.com/questions/21146183/wpf-two-finger-horizontal-scrolling-on-macbook-pro-trackpad

Granted, I didn't really check for any regressions when I added it to WpfMouse, but it's something, potentially. Of course there might be a much simpler way of doing it, but I couldn't see anything off the bat

**Comment by MarcStan** [comment]
Hey, sounds like you already tested out some stuff.

Are you willing to open a PR so I can take a look?
