### ISSUE TITLE
Any plan for .NET 5.0 or .NET Core support?

### ISSUE THREAD

**Issue by charlescao460** [MarcStan/monogame-framework-wpfinterop#26]
Hi,

Thank you for bringing this amazing library to us!

I am just wondering if there's any plan to make this library have a target framework of .NET Core or .NET 5.0. 
 [MonoGame.Framework.WindowsDX](https://www.nuget.org/packages/MonoGame.Framework.WindowsDX/) already supports .NET Core 3.1, and there's no reason to making this library .NET Framework only.  If I understand correctly when referencing .NET Framework from .NET Core or 5.0 there would be a compatibility shim, spending more memory.

**Comment by MarcStan** [comment]
Hey,

Good point, there shouldn't be any blockers.

I'll see if I can get it to multi target all at once in the next couple of weeks.

**Comment by charlescao460** [comment]
Thank you @MarcStan!

**Comment by MarcStan** [comment]
I just released v1.9.0 with support for .Net 4.5.2+, .Net Core 3.1 and .Net 5!
